#!/bin/bash

# OSINT Recon Script by Abdessamad Bourkibate

targets=$(cat targets.txt)
report="recon_report.md"

# بدء التقرير
echo "# OSINT Recon Report" > $report
echo "**Generated by:** Abdessamad Bourkibate" >> $report
echo "**Date:** $(date)" >> $report
echo "" >> $report
echo "---" >> $report
echo "" >> $report

count=1
for target in $targets; do
    echo "## $count. Target: $target" >> $report
    echo "" >> $report

    echo "### 1. TheHarvester Findings" >> $report
    theHarvester -d $target -b bing | tee -a $report
    echo "" >> $report

    echo "### 2. Nmap Scan Results" >> $report
    nmap -sV $target | tee -a $report
    echo "" >> $report

    echo "### 3. Observations and Recommendations" >> $report
    echo "- Add your observations here for $target" >> $report
    echo "" >> $report
    echo "---" >> $report

    ((count++))
done
